#!/usr/bin/python

import pandas as pd
import sys
sys.path.append('../')
from Binance import Binance
import logging.config
import logging.handlers
import logging
import os


# this logging configuration is sketchy
binance = logging.getLogger(__name__)
logging.config.fileConfig('logging.ini')

# create Binance object
bn = Binance()

# set keys
bn.setSecretKey('NhqPtmdSJYdKjVHjA7PZj4Mge3R5YNiP1e3UZjInClVN65XAbvqqM6A7H5fATj0j')
bn.setAPIKey('vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A')


# getAllOrders
print "---------------- getAllOrders --------------"
print "################################# POSITIVE TESTS (returns 1 or r) ###################"
queryParams = {'symbol':'SALTBTC'}
print "****test valid mandatory input symbol, timestamp autogenerated"
test = bn.getAllOrders(queryParams)
print
queryParams = {'symbol':'SALTBTC','timestamp':1507770491000}
print "****test valid mandatory input symbol, timestamp supplied"
test = bn.getAllOrders(queryParams)
print
queryParams = {'symbol':'SALTBTC','recvWindow':123435234,'limit':8}
print "****test valid mandatory input symbol, timestamp autogenerated, optional params"
test = bn.getAllOrders(queryParams)
print
queryParams = {'symbol':'SALTBTC','timestamp':1507770491000,'recvWindow':123435234,'orderId':12345678}
print "****test valid mandatory input symbol, timestamp supplied, optional params"
test = bn.getAllOrders(queryParams)
print

print "################################# NEGATIVE TESTS (returns 0) ###################"
print
queryParams = {'recvWindow':112234}
print "****test valid optional inputs, valid parameter missing"
test = bn.getAllOrders(queryParams)
print
queryParams = {'symbol':12.5,'orderId':3334344}
print "****test valid mandatory inputs present with invalid type"
test = bn.getAllOrders(queryParams)
print
queryParams = {'symbol':'SALTBTC','recvWindow':'123456778','timestamp':150774295}
print "****test valid mandatory inputs, invalid user proved timestamp, plus some optional"
test = bn.getAllOrders(queryParams)
print
queryParams = {'symbol':'ETHBTC','timestamp':'abcdefghijklm'}
print "****test valid mandatory inputs, invalid user proved timestamp type but length ok, plus some optional"
test = bn.getAllOrders(queryParams)
print
queryParams = {'symbol':'ETHBTC','sharkbite':'abcdefghijklm'}
print "****test valid mandatory inputs, random input invalid value"
test = bn.getAllOrders(queryParams)
print
